GigHub/Models/Gig.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GigHub.Models
{
    public class Gig
    {
        public int Id { get; set; }

        public ApplicationUser Artist { get; set; }

        [Required]
        public string ArtistId { get; set; }

        public DateTime DateTime { get; set; }

        [Required]
        [StringLength(255)]
        public string Venue { get; set; }

        public Genre Genre { get; set; }

        [Required]
        public byte GenreId { get; set; }
    }
}

GigHub/ViewModels/GigsViewModel.cs
using GigHub.Models;
using System.Collections.Generic;

namespace GigHub.ViewModels
{
    public class GigsViewModel
    {
        public bool ShowAction { get; set; }
        public IEnumerable<Gig> UpcomingGigs { get; set; }
    }
}

GigHub/Controllers/GigsController.cs
using GigHub.Models;
using GigHub.ViewModels;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace GigHub.Controllers
{
    public class GigsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GigsController()
        {
            _context = new ApplicationDbContext();
        }

        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new GigFormViewModel
            {
                Genres = _context.Geners.ToList()
            };
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GigFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Genres = _context.Geners.ToList();
                return View("Create", viewModel);
            }
            var gig = new Gig
            {
                ArtistId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                GenreId = viewModel.Genre,
                Venue = viewModel.Venue
            };

            _context.Gigs.Add(gig);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult Attending()
        {
            var userId = User.Identity.GetUserId();
            var gigs = _context.Attendances.Where(a => a.AttendeeId == userId)
                .Select(a => a.Gig)
                .Include(g => g.Artist)
                .Include(g => g.Genre)
                .ToList();

            var viewModel = new GigsViewModel()
            {
                UpcomingGigs = gigs,
                ShowAction = User.Identity.IsAuthenticated
            };
            return View(viewModel);
        }

        [Authorize]
        public ActionResult Following()
        {
            var userId = User.Identity.GetUserId();
            var follows = _context.Follows.Where(f => f.FolloweeId == userId)
                .Select(f => f.Followee)
                .ToList();

            var viewMode = new FollowsViewModel()
            {
                Follows = follows,
                ShowAction = User.Identity.IsAuthenticated
            };
            return View(viewMode);
        }
    }
}

GigHub/Views/Gigs/Attending.cshtml
@model GigHub.ViewModels.GigsViewModel
@{
    ViewBag.Title = "Attending";
}

<h2>Attending</h2>
<ul class="gigs">
    @foreach (var gig in Model.UpcomingGigs)
    {
        <li>
            <div class="date">
                <div class="month">@gig.DateTime.ToString("MMM")</div>
                <div class="day">@gig.DateTime.ToString("d ")</div>
            </div>
            <div class="details">
                <span class="artist">
                    @gig.Artist.Name
                </span>
                <span class="genre">@gig.Genre.Name</span>
                @if (Model.ShowAction)
                {
                    <button data-gig-id="@gig.Id" class="btn btn-default btn-sm pull-right js-toggle-attendance">Going</button>
                }

            </div>
        </li>
    }
</ul>

GigHub/Views/Gigs/Create.cshtml
@model GigHub.ViewModels.GigFormViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Add a Gig</h2>
<div>
    @using (Html.BeginForm("Create", "Gigs"))
    {
        <p class="alert alert-info">All fields are <strong>required</strong>.</p>
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(m => m.Venue)
            @Html.TextBoxFor(m => m.Venue, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.Venue)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control", placeholder = "Date, e.g. 1 Jan 2015" })
            @Html.ValidationMessageFor(m => m.Date)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Time)
            @Html.TextBoxFor(m => m.Time, new { @class = "form-control", placeholder = "Time, e.g. 20:00" })
            @Html.ValidationMessageFor(m => m.Time)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Genre)
            @Html.DropDownListFor(m => m.Genre, new SelectList(Model.Genres, "Id", "Name"), new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Genre)
        </div>
        <button type="submit" class="btn btn-success">Save</button>
        <button class="btn btn-secondary-default">Cancel</button>
    }
</div>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

GigHub/Views/Gigs/Following.cshtml
@model GigHub.ViewModels.FollowsViewModel
@{
    ViewBag.Title = "Follows";
}

<h2>Follows</h2>
<ul class="gigs">
    @foreach (var artist in Model.Follows)
    {
        <li>
            <span class="artist">@artist.Name</span>
            @if (Model.ShowAction)
            {
                <button data-gig-id="@artist.Id" class="btn btn-link btn-sm pull-right js-toggle-follow">Unfollow</button>
            }
        </li>
    }
</ul>